---

- name: "templates » fallback | provide nginx fallback vhost for {{ link_name }}.{{ development_tld }}"
  template:
    src: "nginx/fallback.conf.j2"
    dest: "/etc/nginx/conf.d/{{ link_name }}.{{ development_tld }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: service | nginx | restarted
  become: true

- name: "templates » fallback | set var 'nginx_template' when no app was found"
  set_fact:
    nginx_template: "Fallback"