##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: service | nginx | started
  service:
    daemon_reload: yes
    name: nginx
    state: started
  become: true

- name: service | nginx | stopped
  service:
    daemon_reload: yes
    name: nginx
    state: stopped
  become: true

- name: service | nginx | restarted
  service:
    daemon_reload: yes
    name: nginx
    state: restarted
  become: true

- name: service | nginx | reloaded
  service:
    daemon_reload: yes
    name: nginx
    state: reloaded
  become: true

- name: brew | nginx | restarted
  shell: "{{ valet_sh_homebrew_bin }} services restart nginx"
  become: true

- name: brew | nginx | stopped
  shell: "{{ valet_sh_homebrew_bin }} services stop nginx"
  become: true

- name: brew | nginx | started
  shell: "{{ valet_sh_homebrew_bin }} services start nginx"
  become: true